config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/signup", to: "signup#new"
  post "/signup", to: "signup#create"
  # Defines the root path route ("/")
  # root "posts#index"

  get "about", to: "about#aboutus"
  get "impressum", to: "impressum#legalnotice"
  get "dataprotection", to: "dataprotection#dataprotectionpage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def aboutus
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dataprotection_controller.rb
class DataprotectionController < ApplicationController
  def dataprotectionpage
  end
end

app/controllers/impressum_controller.rb
class ImpressumController < ApplicationController
  def legalnotice
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
  end
end

app/controllers/signup_controller_test.rb
require "test_helper"

class SignupControllerTest < ActionDispatch::IntegrationTest
  # test "the truth" do
  #   assert true
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dataprotection_helper.rb
module DataprotectionHelper
end

app/helpers/impressum_helper.rb
module ImpressumHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/about/aboutus.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>About us</strong></h1>
  </div>
</div>

<div>
  <h2>
  Digital Education Bridge e.V. is a fully remote NGO registered as an association in Berlin, Germany. DEB’s aim is to offer free remote education to batches of promising teenagers in developing countries.
  </h2>
  <h2>
  Who we are
  </h2>
  <p>
  Digital Education Bridge has been founded by young Europeans and Latin Americans. We aim to offer new perspectives and opportunities to young people from developing countries. Our members believe in creating prosperity for people through the power of education.
  </p>

  <h2>
  History
  </h2>
  <p>
  The idea of offering free remote classes to children has been born during the global pandemic in 2020. As universities and schools switched to remote classes, it became clear that remote education is possible if necessary.

  Having experienced first-hand that many teenagers in Nicaragua lack the opportunity of learning English, the chairman of the board decided to organise a remote English class for 9 children. This pilot project turned out to be successful - but to finance and scale the future batches, the incorporation of an NGO was needed.

  DEB’s first projects in 2024 are a continuation of the English class, offering the A1 level three times a week for 3 months to chosen batches of teenagers.
  </p>

</div>

app/views/dataprotection/dataprotectionpage.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>Data protection declaration</strong></h1>
  </div>
</div>

<div class="textcontent">
  <h2>
  Datenschutzerklärung
  </h2>

  <p>
  Digital Education Bridge e.V. hat satzungsgemäß die Aufgabe, die Entwicklungszusammenarbeit mithilfe von kostenlosem online-Unterricht zu fördern. Damit wir diese Aufgabe wahrnehmen können, verarbeiten wir personenbezogene Daten von Ihnen. Der Schutz Ihrer personenbezogenen Daten ist uns ein wichtiges Anliegen. Wir verarbeiten diese Daten gemäß Bundesdatenschutzgesetz, EU-Datenschutzgrundverordnung (DSGVO) und Telemediengesetz.
  </p>
  <p>
  Diese Webseite wird vom Digital Education Bridge e.V. betrieben. Er ist Verantwortlicher im Sinne der datenschutzrechtlichen Vorschriften. Bei Fragen und Anregungen hinsichtlich unseres Umgangs mit Ihren Daten wenden Sie sich bitte an die Kontaktadresse in unserem Impressum oder unsere Beauftragte für den Datenschutz unter: info@digitaleducationbridge.org
  </p>

  <p>
  Umgang mit personenbezogenen Daten
  </p>
  <p>
  Wir verarbeiten Ihre personenbezogene Daten, z. B. Name, Kontaktdaten, IP-Adresse oder sonstige Angaben, die mit Ihrer Identität in Verbindung stehen, auf der Grundlage des Art. 6 DSGVO zur Wahrung unseres berechtigten Interesses an der Erfüllung unserer Satzungsaufgabe, zur Erfüllung einer Vereinbarung mit Ihnen oder soweit Sie eingewilligt haben. Wir verwenden Ihre Daten ausschließlich für den Zweck, zu dem Sie uns diese überlassen haben.
  </p>
  <p>
  Bei der Kontaktaufnahme über unser Kontaktformular (verschlüsselte Übertragung) oder per E-Mail werden Ihre Angaben zwecks Bearbeitung der Anfrage sowie für Rückfragen gespeichert.
  </p>
  <p>
  Wenn Sie sich bei uns für eine Mitgliedschaft bewerben, werden Ihre Angaben ausschließlich zur Bearbeitung Ihrer Bewerbung verwendet und nicht an Dritte weitergegeben. Bitte beachten Sie, dass Bewerbungen, die Sie uns per E-Mail senden, unverschlüsselt übertragen werden.
  </p>

  <p>
  Recht auf Auskunft, Berichtigung und Löschung
  </p>
  <p>
  Sie haben das Recht, unentgeltlich Auskunft darüber zu erhalten, ob und welche personenbezogenen Daten wir von Ihnen gespeichert haben, Art. 15 DSGVO. Sollten wir Ihre persönlichen Daten unrichtig gespeichert haben, können Sie die Angaben berichtigen lassen. In den Fällen, in denen wir Ihre persönlichen Daten zur Erfüllung unseres Satzungszwecks gemäß Art. 6 Abs. 1 f) DSGVO verarbeiten, können Sie begründeten Widerspruch gegen diese Verarbeitung einlegen. Soweit keine gesetzlichen Aufbewahrungspflichten entgegen stehen, können Sie jederzeit die Löschung Ihrer Daten verlangen, Art. 17 f. DSGVO. Bitte kontaktieren Sie uns unter: info@digitaleducationbridge.org.
  </p>

  <p>
  Widerruf der Einwilligung
  </p>
  <p>
  Sofern Sie uns eine Einwilligung zur Verarbeitung Ihrer persönlichen Daten erteilt haben, z. B. bei der Anmeldung für unseren elektronischen Newsletter, oder eine Mitgliedschaft, können Sie diese gemäß Art. 7 Abs. 3 DSGVO jederzeit mit Wirkung für die Zukunft widerrufen. Richten Sie Ihren formlosen Widerruf an: info@digitaleducationbridge.org
  </p>

  <p>
  Weitergabe an Dritte
  </p>
  <p>
  Eine Weitergabe Ihrer Daten an Dritte erfolgt nicht.
  </p>

  <p>
  Verwendung von "Cookies"
  </p>
  <p>
  Wie viele andere Internet-Anbieter verwenden wir im Rahmen unseres Online-Angebotes so genannte Cookies. "Cookies" sind Dateien, die für die Dauer Ihres Besuchs auf unserer Webseite auf Ihrem Computer, Smartphone o. ä., gespeichert werden, um festzuhalten, wie Sie sich als Nutzer auf unserer Webseite bewegen. Sie tragen dazu bei, dass Sie z. B. reibungslos navigieren, mehrstufige Bestellvorgänge abwickeln können oder die gewählte Schriftgröße beim Wechsel auf Unterseiten unverändert bleibt.
  </p>
  <p>
  Gängige Web-Browser sind standardmäßig so eingestellt, dass sie "Cookies" akzeptieren. Sie können diese Einstellung verändern, sodass "Cookies" abgelehnt oder vorher eine Bestätigung von Ihnen erfragt wird. Wenn Sie "Cookies" ablehnen, kann es passieren, dass Sie bestimmte Funktionen unseres Online-Angebots nicht mehr vollumfänglich nutzen können.
  </p>

  <p>
  Beschwerderecht
  </p>
  <p>
  Bei offenen Fragen zum Schutz Ihrer personenbezogenen Angaben, die Sie dem Digital Education Bridge e.V. überlassen haben bzw. die der Digital Education Bridge e.V. von Ihnen verarbeitet, nehmen Sie bitte Kontakt mit uns auf unter: info@digitaleducationbridge.org damit wir den Schutz Ihrer Daten prüfen und durchgängig gewährleisten können.
  </p>

  <p>
  Wenn Sie der Ansicht sind, der Digital Education Bridge e.V. verstoße bei der Verarbeitung Ihrer personenbezogenen Daten gegen datenschutzrechtliche Vorschriften, haben Sie das Recht auf Beschwerde bei einer Aufsichtsbehörde. Zuständige Aufsichtsbehörde ist die Berliner Beauftragte für den Datenschutz und Informationsfreiheit, Friedrichstraße 219, 10969 Berlin.
  </p>
</div>

app/views/impressum/legalnotice.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>Legal notice</strong></h1>
  </div>
</div>

<div class="textcontent">
  <h2>
  Impressum
  </h2>
  <p>
  Digital Education Bridge e.V.
  </p>
  <p>
  Gegründet am 12.10.2023 in Berlin.
  </p>
  <p>
  Rechtssitz des Vereins ist Berlin.
  </p>
  <p>
  Satzungsgemäße Aufgabe des Vereins und seiner Mitglieder ist die Förderung der Entwicklungszusammenarbeit. Dieser Zweck wird verwirklicht durch die
  Förderung von Bildungswesen und bevölkerungspolitischen Maßnahmen durch das
  kostenlose Angebot digitaler oder analoger Bildungs- und Unterstützungsangebote in
  Entwicklungsländern, zur Förderung der persönlichen und beruflichen Entwicklung
  der Begünstigten.
  </p>
  <p>
  Email: info@digitaleducationbridge.org
  </p>
  <p>
  Vereinsvorstand:
  </p>
  <p>
  Vorstandsvorsitzender: Nikolai Regehr
  </p>
  <p>
  Vizevorstandsvorsitzende: Fahrina Bestvater
  </p>
  <p>
  Schatzmeister: Maxime Fischer
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DebWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/fontawesome.css"
  integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h3>OLÁ</h3>

app/views/shared/_flashed.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <%= link_to do %>
          <%= image_tag "DEB-preliminary-logo.png", alt: "DEB Logo", style: "width: 50px; height: auto;" %>
        <% end %>
      </div>

      <div class="col-4 footer-links">
        <%= link_to "Legal notice", impressum_path, class: "nav-link" %> | <%= link_to "Data declaration", dataprotection_path, class: "nav-link" %>
      </div>

      <div class="col-4">
        <p>contact: info@digitaleducationbridge.org</p>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <p>© 2024 Digital Education Bridge e.V. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-deb">
  <div class="container-fluid">
    <a href="#" class="navbar-brand">
      <img src="<%= asset_path('DEB-preliminary-logo') %>" alt="deb-logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
         <li>
          <button class="signup-btn">Become a Member</button>
         </li>
         <li class="nav-item dropdown">
          <span class="fa-solid fa-bars" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
          <div class="dropdown-menu dropdown-menu-end languages-dropdown" aria-labelledby="navbarDropdown">
            <%= link_to "About Us", "#", class: "dropdown-item" %>
            <span class="languages__header">Languages</span>
            <div class="flag-images">
              <img src="https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg" alt="German Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png" alt="UK Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/1200px-Bandera_de_Espa%C3%B1a.svg.png" alt="Spain Flag">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1200px-Flag_of_Portugal.svg.png" alt="Portugal Flag">
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/signup/new.html.erb
<div class="banner" background-color="green">
  <div class="container">
    <h1><strong>Support Digital Education Bridge</strong></h1>
  </div>
</div>

<div class="signup-header">
  <h2>Become a member of the Digital Education Bridge e.V.</h2>
  <p>Join us to get involved in projects, follow our development and support us in scaling DEB. Currently there are no membership fees.</p>
</div>


<div class="container" style="background-color: #f0f0f0">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="POST" action="https://script.google.com/macros/s/AKfycbxlPwmxTbnmoDdrY89vr7h709dk_-tRI3FB_oybrT06Fe8Plj76EoAUD4oYCuD9_v3uxw/exec">
        <div class="Form col-md-8">
          <label for="nameinput">Name</label>
          <div class="form-group">
            <input name="First name" type="text" placeholder="First name" required>
            <input name="Last name" type="text" placeholder="Last name" required>
          </div>

          <label for="addressinput">Adress</label>
          <div class="form-group">
            <div class="col">
              <input name="Street & street number" type="text" placeholder="Street & street number" required>
              <input name="Postal code" type="text" placeholder="Postal code" required>
            </div>
            <div class="col">
              <input name="City" type="text" placeholder="City" required>
              <input name="Country" type="text" placeholder="Country" required>
            </div>
          </div>

          <label for="emailinput">Email</label>
          <div class="form-group">
            <input class="form-control-lg" name="Email" type="email" placeholder="Email address" required>
          </div>

          <label for="membershipreasoninput">Why do you want to join us as a member?</label>
          <div class="form-group">
            <textarea class="form-control-lg" name="Your reason to join" type="text" placeholder="Write more than 100 characters" required id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>

          <button type="submit" class="btn btn-primary">Apply for membership</button>

        </div>
      </form>
    </div>
  </div>
</div>


<div class="donate-header">
  <h2>Donate to Digital Education Bridge e.V.</h2>
  <div class="donate-content" style="background-color: #f0f0f0">
    <p>         Coming soon...</p>
  </div>
</div>